---

screen-view:
    x: 0
    y: 0
    w: 640
    h: 480

world-view:
    x: 0
    y: 0
    w: 200
    h: 150

player:
    rect:
        x: 20
        y: 65
        w: 20
        h: 20
    vel:
        x: 0
        y: 0

platforms:
    - rect:
        x: 100
        y: 80
        w: 50
        h: 10
      interactWithPlayer: scream
    - rect:
        x: 80
        y: 100
        w: 50
        h: 10
      interactWithPlayer: scream

